######################################################################
# Automatically generated by qmake (2.01a) ? 7 13 01:37:48 2011
######################################################################

TEMPLATE = vcapp
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += hspide.qrc
